### PR TITLE
add new methods

### PR DESCRIPTION
**Pull request by fricative**
@paul-rs  added method to generate default fixing date when user input settlement date (user can still override this from UI). I have already published the pypi.  thanks.

### CODE REVIEW

**Review by nedlowe — COMMENTED** [review]
"Please make sure the date is a weekend" <- do you mean not a weekend? And this is Mon-Sat right?  Bit random... We should use the workalendar weekend functions (if we can).

**Review by nedlowe — COMMENTED** [review]
For the EUR code - is that something we should wrap somewhere else in this repo or amaasutils (since I can see this piece of code being needed elsewhere) as a single function?

**Review by nedlowe — COMMENTED** [review]
The rest seems good.

**Comment by nedlowe** [comment]
What do you think about that EUR thing?

**Comment by nedlowe** [comment]
And also - did you upload this to PyPI before merged?  If so, I probably just wrote over your version.

**Comment by fricative** [comment]
I concur on the euro thing. I think I published to pypi, last version was Aug 22nd, which was when this request created.

**Comment by nedlowe** [comment]
I will have overwritten it then...

**Review by nedlowe — APPROVED** [review]

**Pull request merged**
